### ISSUE TITLE
Issue with mismatched packages

### ISSUE THREAD

**Issue by johnallen3d** [asdine/cueimports#1]
I've recently discovered your excellent VS Code extension, which I believe will effectively kill my [CUE related extension](https://marketplace.visualstudio.com/items?itemName=jallen7usa.vscode-cue-fmt), and `cueimports`. 👏

One thing that I haven't yet been able to get working is a package that doesn't match the directory name it's contained in (indicated with the [package name after a `:`](https://cuelang.org/docs/concepts/packages/#packages)).

In this contrived example, I have the following structure.

```
❯ lsd --tree
 .
├──  cue.mod
│   ├──  module.cue
│   ├──  pkg
│   └──  usr
├──  foo.cue
└──  hello
    └──  world.cue
```

With a module named `example.com/test`.

```sh
❯ cat cue.mod/module.cue
module: "example.com/test"
```

Inside the `hello` directory I have a package named `world` (real-world use case is dealing with legacy configuration).

```sh
❯ cat hello/world.cue
package world

#person: {
	name: string
}
```

Then I import the `world` package in `foo.cue`.

```sh
❯ cat foo.cue
package foo

import "example.com/test/hello:world"

bar: world.#person & {
	name: "John"
}
```

This works fine when I `cue export`.

```sh
❯ cue export foo.cue --outfile -
{
    "bar": {
        "name": "John"
    }
}
```

However, `cueimports` ditches the import of the `world` package.

```sh
❯ cat foo.cue | cueimports
package foo

bar: world.#person & {
	name: "John"
}
```

I've attached the above in case it helps with troubleshooting.
[cue-playground.zip](https://github.com/asdine/cueimports/files/10288032/cue-playground.zip)

**Comment by asdine** [comment]
Thanks @johnallen3d, I will create the v0.3.0 and include this change to it

**Comment by johnallen3d** [comment]
Hello @asdine, can you confirm if this change was released? I do not see a new [release here on GitHub](https://github.com/asdine/cueimports/releases) but I do see `v0.3.0` on [pkg.go.dev](https://pkg.go.dev/github.com/asdine/cueimports?tab=versions). 

I've tried installing `v0.3.0` like so:

```sh
go install github.com/asdine/cueimports/cmd/cueimports@v0.3.0
```

but when I try to confirm I have the latest version I see `development`

```sh
cueimports -version
development
```

and when I try to test the change I made I see the old behaviour (using example above)

```sh
cat foo.cue | cueimports
package foo

bar: world.#person & {
	name: "John"
}
```

**Comment by johnallen3d** [comment]
FWIW - I'm working to get `cueimports` integrated into Neovim (my preferred editor) which is why I'm keen on what's been released. I've, so far, gotten it added to [mason.nvim](https://github.com/williamboman/mason.nvim/pull/811) which is a package manager of sorts for Neovim.

**Comment by asdine** [comment]
@johnallen3d Sorry for the delay, there was a bug in the v0.3.0 so I deleted it, fixed the bug then recreated it but apparently GitHub caches binaries forever so the old version kept being distributed instead of the new one.
I created a v0.3.1 to fix that.

> FWIW - I'm working to get cueimports integrated into Neovim (my preferred editor) which is why I'm keen on what's been released. I've, so far, gotten it added to https://github.com/williamboman/mason.nvim/pull/811 which is a package manager of sorts for Neovim.

That's amazing! cueimports is going places :)

**Comment by asdine** [comment]
I had to delete it again because there is a problem with the signing of the macos binary. I'll update this thread when it's released again

**Comment by johnallen3d** [comment]
Thanks for looking into this @asdine.

I also had [a PR to null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1315) merged so I'm able to fully take advantage of `cueimports` in Neovim. 😁

**Comment by johnallen3d** [comment]
Hello there @asdine, any chance you're able to get a new release out or is there any way I can help?
